# Generated by Django 3.0.3 on 2020-09-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='city',
        ),
    ]
