# Generated by Django 3.0.3 on 2020-09-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0002_remove_driver_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverequest',
            name='request_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ride_count',
            field=models.IntegerField(default=0),
        ),
    ]
