# Generated by Django 3.0.3 on 2020-09-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0003_auto_20200910_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmeddrive',
            name='request_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
